# docker-compose.yml
services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: foo
      POSTGRES_PASSWORD: foo
      POSTGRES_DB: foodb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - auction_network

volumes:
  postgres-data:

networks:
  auction_network:
    driver: bridge